### ISSUE TITLE
EHN: create a new conditions to compare previous trial effect

### ISSUE THREAD

**Issue by kingjr** [chri4354/Paris_orientation-decoding#17]
The idea would be to test whether  the previous trial(s) (n=1 for now) affect the MEG response of the current trial.

low priority

**Comment by chri4354** [comment]
@kingjr applied to which contrasts? Orientation and visibility? Or all of them?

**Comment by kingjr** [comment]
Orientation and visibility I would say. Let's precise the question: I think we can make a strong hypothesis to test that subjects constantly revise their priors. In such scenario, clearly seeing the orientation a trial `t-1` would bias orientation decoding at trial `t` if `t` is unseen.

**Comment by chri4354** [comment]
Is this akin to the idea of inertia ? http://www.ncbi.nlm.nih.gov/pubmed/24333055

**Comment by kingjr** [comment]
Maybe, I haven't read the paper, could you present it to me next time we
discuss?

**Comment by kingjr** [comment]
https://github.com/kingjr/Paris_orientation-decoding/commit/9c40474f71a6fc80dbd2ea1eb46b67c1ba58bc63
