### ISSUE TITLE
path definition

### ISSUE THREAD

**Issue by kingjr** [chri4354/Paris_orientation-decoding#3]
Prefer avoiding hard links:

in config you should replace the data_path and script_path by
```
base_path = op.dirname(op.dirname(__file__))
data_path = op.join(base_path, 'data')
script_path = op.join(base_path, 'scripts')
results_dir = op.join(base_path, 'results')
```

if you happen to have data somewhere else than where your experiment/scripts are, make a symbolic link.

**Comment by chri4354** [comment]
Actually this is not implemented yet. When I tried to, it crashed, so need debugging.

**Comment by kingjr** [comment]
https://github.com/kingjr/meg_perceptual_decision_symbols/blob/master/toolbox/utils.py
