### ISSUE TITLE
S.E.M

### ISSUE THREAD

**Issue by chri4354** [chri4354/Paris_orientation-decoding#5]
@kingjr 
plot_eb(times, np.mean(scores_diag, axis=0), np.std(scores_diag, axis=0) / np.sqrt(scores.shape[0]), ax=ax, color='blue')

if scores.shape is time * time * subjects, should a correct SEM calculation be over subjects? That is .../np.sqrt(scores.shape[2]), ...

**Comment by kingjr** [comment]
Yes always across the random variable. But note that you can't plot the sem
for a matrix.

**Comment by chri4354** [comment]
yes, this is only for the diagonal performance plot

**Comment by kingjr** [comment]
Ok

**Comment by kingjr** [comment]
Did you find a mistake somewhere?

**Comment by chri4354** [comment]
Yes, in run_stats_decode.py  at least when I load my dataset. Std was divided by the 0th dimension which in my case was time instead of subjects (2nd dimension) to compute sems. Maybe worth checking in your code as well?

**Comment by kingjr** [comment]
Yes indeed, thanks
